services:
  portal-api:
    build:
      context: .
      dockerfile: Portal.Web/Dockerfile
    ports:
      - "5000:8080" # Acessa a API em localhost:5000
    depends_on:
      sqlserver:
        condition: service_healthy

    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PortalDb;User Id=sa;Password=narwal@2026;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver # O nome aqui deve ser o mesmo usado no Server da ConnectionString acima
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=narwal@2026
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'narwal@2026' -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5